spring:
  profiles: default

spring:
  redis:
    host: localhost
    port: 6379

spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

server:
  port: 9090

queue:
  twitter: twitter-track-hashtag
exchange:
  twitter: twitter-track-exchange
routing_key:
  track: "*"

---

spring:
  profiles: docker

spring:
  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest
    port: 5672

spring:
  redis:
    host: redis
    port: 6379

server:
  port: 9090

queue:
  twitter: twitter-track-hashtag
exchange:
  twitter: twitter-track-exchange
routing_key:
  track: "*"
