
server:
  port: 50008
  
management:
  port: -1

endpoints:
  shutdown:
    enabled: true
  health:
    sensitive: false
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

turbine:
  stream:
    port: 50007
  aggregator:
    clusterConfig: ALL
  appConfig: flights,planes,passengers,gateway,fares

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
