twitter:
  consumer-key: ${consumer-key}
  consumer-secret: ${consumer-secret}
  access-token: ${access-token}
  access-token-secret: ${access-token-secret}

spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

queue:
  twitter: twitter-stream
exchange:
  twitter: twitter-exchange